### ISSUE TITLE
[templates] ログイン画面

### ISSUE THREAD

**Issue by massu116** [Funcy-ICT/Funcy_Portfolio_iOS_for_SwiftUI#26]
## 目的
- MVVMアーキテクチャのサンプルとして実装
## Taskリスト
- サーバ通信ちゃんとやってね💞
## Doneの定義
- 
<img width="177" alt="スクリーンショット 2022-10-03 17 43 45" src="https://user-images.githubusercontent.com/49420598/193536299-8c9dfd5b-1af0-44b8-a0ff-818a1cb1aadb.png">

## 参考
- 
## 留意事項
- 
## 検討事項
-

**Comment by KaitoKudou** [comment]
async/await使って実装しようね💞
