### ISSUE TITLE
[Atom fix] TextFieldの修正対応

### ISSUE THREAD

**Issue by zekuta-x** [Funcy-ICT/Funcy_Portfolio_iOS_for_SwiftUI#32]
## 目的
- TextField でパスワードを入力するとき、丸見え
## Taskリスト
- TextBoxに隠すようのフラグを作る
## Doneの定義
- 入力内容が隠れるものを作る

**Comment by mersakakey** [comment]
https://github.com/Funcy-ICT/Funcy_Portfolio_iOS_for_SwiftUI/pull/65

ここで対応したのでmerge
